micronaut:
  metrics:
    enabled: true
  application:
    name: server
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  prometheus:
    sensitive: false
client:
  base-url: 'http://localhost:8080'